openapi: 3.2.0
info:
  title: Rokt Catalog Markets API
  version: 1.0.1
  description: Integrate with Rokt Catalog
servers:
- url: https://api.shopcanal.com/platform
  description: Rokt Catalog Storefront Public API
tags:
- name: Markets
paths:
  /markets/prices/import/:
    post:
      operationId: markets_prices_import_create
      tags:
      - Markets
      security:
      - basicAuth: []
      - platformAppId: []
        platformAppToken: []
      - {}
      responses:
        '200':
          description: No response body
      summary: Markets prices import create
      x-summary-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    platformAppId:
      type: apiKey
      in: header
      name: X-CANAL-APP-ID
    platformAppToken:
      type: apiKey
      in: header
      name: X-CANAL-APP-TOKEN
